sudo: required

services:
  - docker
  - kubectl 

env:
  global:
    - IMAGE_NAME=dchinchure/travis-docker

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
    chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    
script:
  - docker build --tag "$IMAGE_NAME" .
  - docker login -u "$REGISTRY_USER" --password "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker push "${IMAGE_NAME}:latest"
  - docker pull dchinchure/travis-docker
  - export KUBECONFIG=mykubeconfig
  - kubectl run toy --image=dchinchure/travis-docker
  - kubectl expose deployment/toy --type=NodePort --port=8080 --name=toy-service --target-port=8080
  - kubectl describe service toy-service
